Repository SystemConsultantGroup/ICC-grad-dissertion-manage-backend, pull requests merged in 2024-05, with the labels that each got.

#115 [FEAT] 학생, 교수, 학과 삭제 로직 변경 / 디비 스키마에 onDelete 조건들 추가
  prisma/schema.prisma
  src/modules/departments/departments.controller.ts
  src/modules/departments/departments.module.ts
  src/modules/departments/departments.service.ts
  src/modules/files/files.module.ts
  src/modules/students/students.controller.ts
  src/modules/students/students.module.ts
  src/modules/students/students.service.ts
Labels: :rocket: feature, fix

#119 [FIX] 최종심사결과보고서 학과 정보 누락 수정
  src/modules/reviews/reviews.service.ts
Labels: :lady_beetle: bug

#114 [FIX] 논문 정보 하나에 리뷰가 너무 많이 생기는 문제 수정
  src/modules/students/students.service.ts
Labels: fix

#116 [FIX] Implement professor bulk insert logic
  src/modules/professors/professors.service.ts
Labels: :lady_beetle: bug

#117 [FIX] 심사 보고서 제출 에러 수정
  src/modules/reviews/reviews.service.ts
Labels: :lady_beetle: bug

#118 [FIX] 학생/교수 엑셀 양식, 참고 사항 수정
  resources/excel/연구논문작품시스템_교수_일괄등록_양식.xlsx
  resources/excel/연구논문작품시스템_학생_일괄등록_양식.xlsx
Labels: :lady_beetle: bug, fix

#128 [FIX] 학생 지도 관계 업데이트 오류 수정
  src/modules/students/students.service.ts
Labels: :lady_beetle: bug, fix

#125 [HOTFIX] 심사의견 양식 수정 / 최종판정 심사의견 확인 가능하도록 수정
  resources/format/심사결과보고서_양식.html
  resources/format/심사보고서_양식.html
  resources/format/예비심사결과보고서_양식.html
  resources/format/예비심사보고서_양식.html
  src/modules/reviews/dtos/review.dto.ts
Labels: :lady_beetle: bug

#124 [FIX] 학생 엑셀 대량 등록 에러 수정
  src/modules/students/students.service.ts
Labels: :lady_beetle: bug, fix

#129 fix: 심사논문 관련 추가 수정
  src/modules/reviews/reviews.service.ts
Labels: :lady_beetle: bug

#130 [FIX] 특정 학과 학생 논문 정보 업데이트 오류 수정
  src/modules/students/students.service.ts
  src/modules/theses/theses.service.ts
Labels: :lady_beetle: bug, fix
