Repository SystemConsultantGroup/ICC-grad-dissertion-manage-backend, pull requests merged in 2024-07, with the labels that each got.

#136 [FIX] achievement 등록 오류 해결
  prisma/schema.prisma
  src/modules/achievements/achievements.controller.ts
Labels: :lady_beetle: bug, fix

#137 [FIX] 최종심사보고서 예심 서명 누락 수정
  src/modules/reviews/reviews.service.ts
Labels: :lady_beetle: bug, fix

#140 [FIX] 최종판정 제목 미표기 문제 해결
  src/modules/reviews/dtos/get-review-final.res.dto.ts
Labels: :lady_beetle: bug

#142 feat: review list 내용 변경
  src/modules/reviews/reviews.service.ts
Labels: :lady_beetle: bug, :rocket: enhancement, :rocket: feature

#144 [FIX] 뉴라인 캐릭터에 br태그 추가
  src/modules/reviews/reviews.service.ts
Labels: :lady_beetle: bug
