Repository SystemConsultantGroup/ICC-grad-dissertion-manage-backend, pull requests merged in 2024-04, with the labels that each got.

#102 [FEAT] 학생 전체 삭제 추가
  src/modules/students/students.controller.ts
  src/modules/students/students.service.ts
Labels: :rocket: enhancement

#103 [FIX] 학생 일괄 업로드 양식 참고사항 수정
  resources/excel/연구논문작품시스템_학생_일괄등록_양식.xlsx
Labels: fix

#105 feat: modify loginId type
  resources/excel/연구논문작품시스템_교수_일괄등록_양식.xlsx
  resources/excel/연구논문작품시스템_학생_일괄등록_양식.xlsx
  src/modules/professors/dtos/professor.dto.ts
  src/modules/professors/dtos/professors-list-query.dto.ts
  src/modules/professors/dtos/upload-professor.dto.ts
  src/modules/students/students.service.ts
Labels: :rocket: feature

#106 [FIX] 서명 파일 없을때 예외처리
  src/modules/reviews/reviews.service.ts
Labels: fix
